<a href="https://colab.research.google.com/github/nomanGondal/LogisticRegression/blob/main/numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr =np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [ ]:

print(arr[2])


3


### **Dimensionalities**

In [ ]:
arr1=np.array(20) #zero dim..
print(arr1)


20


In [ ]:
print(arr1.shape)

()


In [ ]:
arr=np.array([20,45]) #1D
print(arr)

[20 45]


In [ ]:
print(arr.shape)

(2,)


In [ ]:
print(arr1.ndim)

1


In [ ]:
arr1=np.array([[20,30,40,50],[9,8,5,5],[2,3,4,5]]) #1D note: the no. of values are equals in all dim..
print(arr1)

[[20 30 40 50]
 [ 9  8  5  5]
 [ 2  3  4  5]]


In [ ]:
print(arr1.shape)

(3, 4)


In [ ]:
print(arr1.ndim)

2


In [ ]:
arr_3d=np.array([[[20,30,40,50],[9,8,5,5],[2,3,4,5]],[[20,30,40,50],[9,80,5,5],[2,3,4,5]]]) #3D note: In NumPy, a 3D array is like a collection of 2D arrays stacked on top of each other
print(arr_3d)

[[[20 30 40 50]
  [ 9  8  5  5]
  [ 2  3  4  5]]

 [[20 30 40 50]
  [ 9 80  5  5]
  [ 2  3  4  5]]]


In [ ]:
print(arr_3d.ndim)

3


In [ ]:
print(arr_3d.shape) #2 → Number of layers
#3 → Rows in each layer
#4 → Columns in each row

(2, 3, 4)


In [ ]:
print(arr_3d[1][1][1])  #[layer][row][column]

80


In [ ]:
ones_3d = np.ones((2, 6, 4))
print(ones_3d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


**note:**
np.array() for manual creation
np.arange() + .reshape() for sequential numbers
np.zeros() and np.ones() for arrays filled with zeros or ones

In [ ]:
arr_nd=np.array([1,2,3,4,5] ,ndmin=6) #n dimensions array (no. of sequare bracelets show the no. dims)
print(arr_nd)
print(arr_nd.shape)

[[[[[[1 2 3 4 5]]]]]]
(1, 1, 1, 1, 1, 5)


.ndim → Number of dimensions

.shape → Shape of the array (rows, columns, etc.)

.size → Total number of elements

.dtype → Data type of elements

In [ ]:
arr_fun = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_fun.ndim)
print(arr_fun.shape)
print(arr_fun.size)
print(arr_fun.dtype)

2
(2, 3)
6
int64


In [ ]:
random_arr=np.random.rand(2, 3) #random creation of array
print(random_arr)

[[0.51696793 0.8836648  0.98320292]
 [0.05016721 0.24359477 0.16098788]]


In [ ]:
random_arrint = np.random.randint(0, 10, (2, 3)) #control the type of data
print(random_arrint)

[[8 7 8]
 [7 0 4]]


In [ ]:
arr11=np.array([1,2,3,4,5,6,7,8,9,10]) #sum of two arrays
arr22=np.array([1,2,3,4,5,6,7,8,9,10])
arr_sum=arr11+arr22
print(arr_sum)

[ 2  4  6  8 10 12 14 16 18 20]


**Join of two array**

In [ ]:
arr11=np.array([1,2,3,4,5,6,7,8,9,10]) #sum of two arrays
arr22=np.array([1,2,3,4,5,6,7,8,9,10])
arr_con=np.concatenate((arr11,arr22))
print(arr_con)

[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]


close : slicing and concatenate are pendaning for practical

# **concatenate 1D array**

In [ ]:
arr_1= np.array([1, 2, 3])   # Shape: (3,)
arr_2 = np.array([4, 5, 6])   # Shape: (3,)

result = np.concatenate((arr_1, arr_2))
print(result)


[1 2 3 4 5 6]


# concatenate 2D array

1D + 1D → Directly possible.

2D + 2D → Possible if row/column sizes match.

3D + 3D → Possible if the shape matches except along the concatenation axis.

1D + 2D + 3D → Requires reshaping (expand_dims() or reshape()).

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
arr2 = np.array([[7, 8, 9], [10, 11, 12]])  # Shape: (2, 3)
result = np.concatenate((arr1, arr2), axis=0)  # Concatenating row-wise
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr1c = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
arr2c = np.array([[7, 8, 9], [10, 11, 12]])  # Shape: (2, 3)
result = np.concatenate((arr1, arr2), axis=1)  # Concatenating column-wise

print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# **3D**

In [ ]:
arr1 = np.array([[[1, 2], [3, 4]]])   # Shape: (1, 2, 2)
arr2 = np.array([[[5, 6], [7, 8]]])   # Shape: (1, 2, 2)

result = np.concatenate((arr1, arr2), axis=0)  # Concatenating along depth
print(result)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# ✂#**slicing**

Slicing means extracting specific portions of an array using index ranges.

It allows us to work with subarrays without modifying the original array.

array[start:stop:step]

start → The index where slicing starts (inclusive).

stop → The index where slicing stops (exclusive).

step → Defines the step size (default is 1).


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
s_arr=arr[1:5]
print(s_arr)  # Slicing from index 1 to 4

[20 30 40 50]


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
s_arr=arr[0:6:2]
print(s_arr)  #0, 0+2=2, 2+2=4,

[10 30 50]


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[:4])   # From start to index 3
print(arr[3:])   # From index 3 to end
print(arr[::2])  # Every 2nd element


[10 20 30 40]
[40 50 60 70]
[10 30 50 70]


 **Negative indexing**
 negative indexing start from 1

In [ ]:
print(arr[-4:-1])  # From 4th last to 2nd last element
print(arr[::-1])   # Reverse the array

[40 50 60]
[70 60 50 40 30 20 10]


## **Slicing in 2D**

array[row_start:row_end, column_start:column_end]


In [ ]:
arr2D = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
print(arr2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr2D[1: , 2:])

[[ 7  8]
 [11 12]]


In [ ]:
print(arr2D[1, :])  # Entire 2nd row(single row)

[5 6 7 8]


In [ ]:
print(arr2D[:, 2])  # Entire 3rd column


[ 3  7 11]


In [ ]:
print(arr2D[::2, ::2])  # Every alternate row & column


[[ 1  3]
 [ 9 11]]


### **3D**

array[depth_start:depth_end, row_start:row_end, column_start:column_end]


# **Note: **
👉 Slicing returns a view, not a copy.

Modifying the slice modifies the original array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
slice_arr = arr[1:4]
slice_arr[:] = 99  # Modify slice
print(arr)  # Original array is also modified

[ 1 99 99 99  5]


# **Solution: **
Use .copy() to avoid modifying the original array.

In [ ]:
copy_arr = arr[1:4].copy()
copy_arr[:] = 50
print(arr)  # Original remains unchanged


[ 1 99 99 99  5]


## **Fancy Indexing & Boolean Masking**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])   # Selecting Specific Indices (Fancy Indexing)
print(arr[[0, 2, 4]])  # Selecting elements at indices 0, 2, and 4


[10 30 50]


In [ ]:
#boolean Masking

arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Find elements greater than 25
print(arr[mask])

[30 40 50]


## **splitting**
Splitting in NumPy means dividing an array into multiple sub-arrays.

 It is the opposite of concatenation. NumPy provides different functions to split arrays based on the number of parts or specific indices.

=> Splitting Returns a Copy (Independent Arrays)

When you split an array, each sub-array is a separate copy.
Changes in the split arrays do not affect the original array.

 Use split() for equal splits, array_split() for unequal splits.

 Use vsplit(), hsplit(), and dsplit() for 2D/3D arrays.

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
split_arr = np.split(arr, 3)  # Split into 3 equal parts
print(split_arr)


[array([10, 20]), array([30, 40]), array([50, 60])]


In [ ]:
split_arr = np.split(arr, [2, 4])  # Split at index 2 and 4
print(split_arr)


[array([10, 20]), array([30, 40]), array([50, 60])]


# Handling Unequal Splitting – array_split()

In [ ]:
split_arr = np.array_split(arr, 4)  # Splitting into 4 unequal parts
print(split_arr)


[array([10, 20]), array([30, 40]), array([50]), array([60])]


In [ ]:
c=np.array([[[1,2,3]]])
print(c)
print(c.ndim)
print(c.shape)

[[[1 2 3]]]
3
(1, 1, 3)


In [ ]:
d=c.ravel()  #ravel function Convert multiDim  into 1D (flattened)
print(d.ndim)
print(d)


1
[1 2 3]


In [ ]:
#and if we convert 3d into 2d then use reshape instead

arr3D = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

print(arr3D.ndim)

3


In [ ]:
arr2D=arr3D.reshape(-1,4)
print(arr2D.ndim)

2


# **unique function**
The numpy.unique() function is used to find unique elements in an array and return them in a sorted order.
It is useful for removing duplicates from an array.

Note:Works on 1D, 2D, and higher-dimensional arrays but always returns unique elements in 1D format.

In [ ]:
#syntax: numpy.unique(arr, return_index=False, return_counts=False, return_inverse=False)
#arr--------------->	Input array
#return_index	----->If True, returns the indices of the first occurrences of unique values
#return_counts----->	If True, returns the count of each unique element


In [ ]:
arr=np.array([1,2,3,4,4,4,2,6,1,1,6,5,7,8,5])
unique_values=np.unique(arr)
print(unique_values)

[1 2 3 4 5 6 7 8]


In [ ]:
unique_values,idx=np.unique(arr,return_index=True)
print(unique_values)
print(idx)

[1 2 3 4 5 6 7 8]
[ 0  1  2  3 11  7 12 13]


In [ ]:
unique_values,count=np.unique(arr,return_counts=True)
print(unique_values)
print(count)

[1 2 3 4 5 6 7 8]
[3 2 1 3 2 2 1 1]


# **Delete :syntax----> numpy.delete(arr, obj, axis=None)**
if axis is none then delete row wise if 1 then delete columns wise

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
new_arr = np.delete(arr, 2)  # Delete the element at index 2 (30)

print(new_arr)

[10 20 40 50]


In [ ]:
arr2D = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

new_arr = np.delete(arr2D, 1, axis=0)  # Delete the 2nd row (index 1)
print(new_arr)

[[1 2 3]
 [7 8 9]]


In [ ]:
new_arr = np.delete(arr2D, 1, axis=1)  # Delete the 2nd column (index 1)
print(new_arr)

[[1 3]
 [4 6]
 [7 9]]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
new_arr = np.delete(arr, [1, 3])  # Delete elements at indices 1 and 3
print(new_arr)

[10 30 50]
